### ISSUE TITLE
DLL Load Failed (again) version >= 3.0.1

### ISSUE THREAD

**Issue by aulon** [osmcode/pyosmium#158] opened 2020-11-20 09:57 UTC
Hi everyone, 
I saw the closed thread here (https://github.com/osmcode/pyosmium/issues/98) and I wanted to share that the issue still shows up. I installed `osmium` some time in November and it worked fine. Two weeks later, I try to install it on another pc and I get the following error: 
`File [...]\Anaconda3\envs\osmium38\lib\site-packages\osmium\__init__.py, line 1
from osmium.__osmium import *
ImportError: DLL load failed while importing _osmium: The specified module could not be found`

I created 3 test conda environments with the following python version:

1. python = 3.6 --> osimum==2.15.4 works, anything above does not
2. python = 3.7 --> osimum==2.15.4 works, anything above does not
3. python = 3.8 --> could not get version 3.1.0, 3.0.1, and 2.15.4 to work.

Could you please look into it and let me know if there are any fixes?

Thank you!

**Comment by lonvia** [comment] 2020-11-20 10:11
Closing as duplicate of #148.

**Closed by lonvia** 2020-11-20 10:11 UTC
