### ISSUE TITLE
Creating geographic extracts

### ISSUE THREAD

**Issue by JohnENoonan** [osmcode/pyosmium#198] opened 2022-03-29 21:36 UTC
Hi, I'm looking to create geographical extracts [just like you would with osmium-tool](https://osmcode.org/osmium-tool/manual.html#creating-geographic-extracts). The functionality I'm looking for is 
```osmium extract -b 2.25,48.81,2.42,48.91 france.pbf -o paris.pbf```. 
Is that something that is doable with pyosmium? I looked through the documentation but didn't see something similar. Thanks!

**Comment by lonvia** [comment] 2022-03-30 07:16
No, pyosmium doesn't have that option.

Closing as duplicate of #191.

**Closed by lonvia** 2022-03-30 07:16 UTC

**Comment by district10** [comment] 2022-05-13 04:49
I integrated osmium-tool alongside pyosmium (they have almost same dependency and the integration is simple) by adding `src/osmium/__main__.py`:

```python
import sys
import os

if __name__ == '__main__':
    pwd = os.path.abspath(os.path.dirname(__file__))
    exe = f'{pwd}/osmium'
    if not os.path.isfile(exe):
        raise Exception(f'{exe} not found, osmium-tool not integrated')

    cmd = ' '.join([exe, *sys.argv[1:]])
    print(f'$ {cmd}')
    cmd = f'LD_LIBRARY_PATH={pwd}:$LD_LIBRARY_PATH {cmd}'
    sys.exit(os.system(cmd))
```

Then add this compiled executable `osmium` from osmium-tool to pyosmium pip package. Edit setup.py:

```python
    package_data={
        PROJECT_NAME: so_files + ['osmium'], # install osmium binary alongside other shared libs
    },
```

Then you have:

```bash
python3 -m osmium fileinfo osmium-test/input.osm
```

Seems like a good idea.

**Comment by district10** [comment] 2022-05-14 07:08
@lonvia @joto How about integrate osmium-tool into pyosmium? :smiley: 

Compiling by hand is hard, getting a pip package is easy.

**Comment by ImreSamu** [comment] 2022-05-14 09:34
@district10 
> Compiling by hand is hard, getting a pip package is easy.


https://anaconda.org/conda-forge/osmium-tool  
_"To install this package with conda run:"_   `conda install -c conda-forge osmium-tool`
* **osx-64; linux-64; win-64**
* v1.14.0

**Comment by district10** [comment] 2022-05-14 09:38
@ImreSamu :cry: ... I missed that. Thank you.
