### ISSUE TITLE
Deprecation warning on python 3.7

### ISSUE THREAD

**Issue by knaveofdiamonds** [osmcode/pyosmium#114] opened 2019-10-01 15:05 UTC
Importing osmium and running with warnings turned on or running under pytest produces the following deprecation warning on python 3.7.4 and 3.7.3:

    _frozen_importlib:219: DeprecationWarning: __int__ returned non-int (type bool).  The ability to return an instance of a strict subclass of int is deprecated, and may be removed in a future version of Python.

To replicate, create a file foo.py with:

    import osmium

And then run `python -Wd foo.py`.

I can't see anything obvious in any of the python code, maybe this is something in the C++ bindings (which I don't know much about)?

**Comment by lonvia** [comment] 2019-10-01 17:18
The problem is with the bool-typed `enum class`es osmium:geom:use_nodes and osmium:geom:direction. pybind11 seems to not properly translate them into their underlying type. There is a [similar issue about char-typed enums](https://github.com/pybind/pybind11/issues/1820) and a [PR with a fix for it](https://github.com/pybind/pybind11/pull/1334). So I guess this needs digging into pybind11.

**Comment by lonvia** [comment] 2022-03-22 08:47
I can confirm that this is fixed with the latest pybind11 versions.

**Closed by lonvia** 2022-03-22 08:47 UTC
