### ISSUE TITLE
apply_file not terminating once the processing is complete 

### ISSUE THREAD

**Issue by pradeepgudipati** [osmcode/pyosmium#246] opened 2024-05-17 10:31 UTC
Here are more details. 

https://github.com/osmcode/pyosmium/discussions/233

**Comment by lonvia** [comment] 2024-05-17 12:07
Please do not double report your issues. It won't make it more likely that you get an answer.

Closing as duplicate and for missing any usable description of the problem.

**Closed by lonvia** 2024-05-17 12:07 UTC

**Comment by kubatjak** [comment] 2024-05-17 12:26
Dear @lonvia, 
I don't think it's double reporting of an issue. Originally, I have posted this as a discussion. Since then more people have reported the same problem which makes it worth to turn it into an issue, I believe. My Issue was already closed before (it included the full description btw), now this one from @pradeepgudipati. If you believe it will get the same amount of attention from contributors in Discussions I am happy leaving it there. But otherwise, I would like to move it to Issues. What do you think is the correct procedure to do that? Thank you very much for your time and for any reply!

**Comment by kubatjak** [comment] 2024-05-17 15:04
I am not sure whether we understand each other. So you are saying you treat both Discussion and Issue as an Issue? Because at no point in time there was a duplication of any Issue on this topic.
Cheers

**Comment by ImreSamu** [comment] 2024-05-17 18:20
@kubatjak ,  @pradeepgudipati

Please, instead of repeatedly bringing up a one-year-old, poorly documented issue without new information, 
invest your energy in debugging the problem and demonstrate your genuine interest in finding a solution. 

For example, this program should work:
*  https://github.com/osmcode/pyosmium/blob/master/examples/osm_file_stats.py
If it doesn't, the issue might be with 
   * the input data 
   * or your (python) environment.

### In next time please provide all relevant information for any pyosmium software issue!

#### 1. Environment:
  - OS Version: Specify your operating system and version.
  - Hardware Specs: Indicate your hardware specifications, including architecture (32-bit or 64-bit, ARM, x86-64, etc.).
  - Python Version: Indicate the Python version(s) you're using.
  - Installation Method: Describe how Pyosmium was installed in your setup.

#### 2. Example Programs is working?
- Verification: Confirm that the example programs from Pyosmium's repository work in your environment.
   -  https://github.com/osmcode/pyosmium/tree/master/examples

#### 3. Documentation Check
- Before submitting a report, please ensure you have checked the [Pyosmium Documentation](https://docs.osmcode.org/pyosmium/latest/) for a potential solution to your issue.

#### 4. Please create a minimal reproducible example
- Code: Include the smallest snippet of code that still exhibits the bug.
- OSM File: Attach a minimal OSM file that replicates the issue.

#### 5. Input File Integrity
- Verification Process: Describe how you confirmed that the input OSM file is neither broken nor badly formatted.
    - https://docs.osmcode.org/osmium/latest/osmium-check-refs.html
    
#### 6. Debugging Steps
- Environment Testing: List any attempts to reproduce the issue in different environments (e.g., on a Linux system).
- Diagnostic Efforts: Detail what you have tried in order to isolate or fix the bug.

#### 7. Retesting as you can:
- Multiple Python Versions: Test the issue across various Python versions (from 3.9 to 3.12).
- Pyosmium Versions: Check the bug against multiple versions of Pyosmium (from 3.5 to 3.7).
- Different Data Sets: Use various input data to assess if the issue persists across different scenarios.

#### 8. Additional Information
- Logs and Outputs: Provide any relevant logs, error messages, or outputs that might help diagnose the problem.
- Communication: Keep your descriptions factual and objective to facilitate efficient problem-solving.

**Comment by kubatjak** [comment] 2024-05-17 18:29
@ImreSamu
😀 😀 😀 thank you
